#!/usr/bin/env python3
"""Resolve an Agent-generated route plan with deterministic registry data."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Mapping


ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "registry"
SCENES = {"bug-fix", "open-source", "academic", "community"}
INTERACTION_MODES = {"direct", "clarify"}
DEPTHS = {"light", "medium", "deep"}
REQUIREMENT_FIELDS = (
    "target",
    "goal",
    "capabilities",
    "context",
    "constraints",
    "evidence",
    "time",
    "explicit_platforms",
)


class PlanError(ValueError):
    """Raised when an Agent plan cannot be resolved safely."""


def read_json(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise PlanError(f"cannot read JSON registry {path}: {exc}") from exc


def registry_platform_ids() -> set[str]:
    index = read_json(REGISTRY / "platforms.index.json")
    active = {item for item in index.get("platforms", []) if isinstance(item, str)}
    catalog = {
        item.get("platform_id")
        for item in index.get("catalog_only_platforms", [])
        if isinstance(item, dict) and isinstance(item.get("platform_id"), str)
    }
    return active | catalog


def registry_aliases() -> dict[str, str]:
    data = read_json(REGISTRY / "aliases.json")
    aliases = data.get("aliases")
    if not isinstance(aliases, dict):
        raise PlanError("registry/aliases.json must contain an aliases object")
    return {str(alias).strip().casefold(): target for alias, target in aliases.items()}


def canonicalize_platform(value: str) -> str:
    """Map one Agent-supplied platform name to a registered canonical id."""

    if not isinstance(value, str) or not value.strip():
        raise PlanError("platform_id must be a non-empty string")
    candidate = value.strip().casefold()
    platform_ids = registry_platform_ids()
    if candidate in {item.casefold() for item in platform_ids}:
        return next(item for item in platform_ids if item.casefold() == candidate)
    target = registry_aliases().get(candidate)
    if target in platform_ids:
        return target
    raise PlanError(f"unknown platform alias or id: {value!r}")


def _string_list(
    value: Any,
    field: str,
    *,
    allow_empty_list: bool = True,
    allow_empty_items: bool = False,
) -> list[str]:
    if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
        raise PlanError(f"{field} must be a list of strings")
    result = [item.strip() for item in value]
    if not allow_empty_list and not result:
        raise PlanError(f"{field} must contain at least one item")
    if not allow_empty_items and any(not item for item in result):
        raise PlanError(f"{field} cannot contain empty strings")
    return result


def normalize_requirement(value: Any) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise PlanError("requirement must be an object generated by the Agent")
    missing = [field for field in REQUIREMENT_FIELDS if field not in value]
    if missing:
        raise PlanError(f"requirement is missing fields: {', '.join(missing)}")
    result: dict[str, Any] = {}
    if not isinstance(value["target"], str) or not isinstance(value["goal"], str):
        raise PlanError("requirement.target and requirement.goal must be strings")
    result["target"] = value["target"].strip()
    result["goal"] = value["goal"].strip()
    for field in REQUIREMENT_FIELDS[2:-1]:
        result[field] = _string_list(value[field], f"requirement.{field}")
    explicit = _string_list(value["explicit_platforms"], "requirement.explicit_platforms")
    result["explicit_platforms"] = []
    for platform in explicit:
        canonical = canonicalize_platform(platform)
        if canonical not in result["explicit_platforms"]:
            result["explicit_platforms"].append(canonical)
    return result


def load_platform(platform_id: str) -> dict[str, Any]:
    path = REGISTRY / "platforms" / f"{platform_id}.json"
    if path.is_file():
        data = read_json(path)
        if not isinstance(data, dict):
            raise PlanError(f"platform registry entry must be an object: {platform_id}")
        return data
    index = read_json(REGISTRY / "platforms.index.json")
    for entry in index.get("catalog_only_platforms", []):
        if isinstance(entry, dict) and entry.get("platform_id") == platform_id:
            return entry
    raise PlanError(f"platform registry entry is missing: {platform_id}")


def complete_dispatch_packet(
    agent_platform: Any,
    *,
    requirement: Mapping[str, Any],
    depth: str,
) -> dict[str, Any]:
    if not isinstance(agent_platform, dict):
        raise PlanError("each platform plan must be an object")
    if "platform_id" not in agent_platform:
        raise PlanError("platform plan is missing platform_id")
    platform_id = canonicalize_platform(agent_platform["platform_id"])
    entry = load_platform(platform_id)
    require_queries = agent_platform.get("_require_queries", False)
    queries = _string_list(
        agent_platform.get("queries", []),
        f"platforms[{platform_id}].queries",
        allow_empty_list=not require_queries,
    )
    routes = entry.get("depth_routes")
    if isinstance(routes, dict):
        skill_order = routes.get(depth)
    else:
        skill_order = entry.get("route_skills", [])
    if not isinstance(skill_order, list) or not all(isinstance(item, str) for item in skill_order):
        raise PlanError(f"platform registry has no valid Skill route for {platform_id}/{depth}")

    agent_id = agent_platform.get("agent_id") or f"{platform_id}-agent"
    if not isinstance(agent_id, str) or not agent_id.strip():
        raise PlanError(f"platforms[{platform_id}].agent_id must be a non-empty string")
    goal = agent_platform.get("goal", requirement["goal"])
    if not isinstance(goal, str):
        raise PlanError(f"platforms[{platform_id}].goal must be a string")
    evidence = agent_platform.get("evidence", requirement["evidence"])
    evidence = _string_list(evidence, f"platforms[{platform_id}].evidence")
    stop_condition = agent_platform.get("stop_condition", "")
    if not isinstance(stop_condition, str):
        raise PlanError(f"platforms[{platform_id}].stop_condition must be a string")
    status = agent_platform.get("status", entry.get("status", "planned"))
    if not isinstance(status, str):
        raise PlanError(f"platforms[{platform_id}].status must be a string")

    packet = {
        "platform_id": platform_id,
        "agent_id": agent_id,
        "tier": entry.get("tier"),
        "depth": depth,
        "queries": queries,
        "skill_order": list(skill_order),
        "scripts": list(entry.get("scripts", [])),
        "search_components": list(entry.get("search_components", [])),
        "adapter_type": entry.get("adapter_type"),
        "access_mode": entry.get("access_mode"),
        "depth_routes": routes if isinstance(routes, dict) else {},
        "status": status,
        "goal": goal.strip(),
        "evidence": evidence,
        "stop_condition": stop_condition.strip(),
    }
    if "selection_reason" in agent_platform:
        if not isinstance(agent_platform["selection_reason"], str):
            raise PlanError(f"platforms[{platform_id}].selection_reason must be a string")
        packet["selection_reason"] = agent_platform["selection_reason"]
    return packet


def resolve_route_plan(value: Any) -> dict[str, Any]:
    """Complete an Agent plan without interpreting natural-language input."""

    if not isinstance(value, dict):
        raise PlanError("the planner input must be a JSON object generated by the Agent")
    requirement = normalize_requirement(value.get("requirement"))
    for field, allowed in (("scene", SCENES), ("interaction_mode", INTERACTION_MODES), ("depth", DEPTHS)):
        if value.get(field) not in allowed:
            raise PlanError(f"{field} must be one of: {', '.join(sorted(allowed))}")
    interaction_mode = value["interaction_mode"]
    if interaction_mode == "direct":
        for field in ("target", "goal"):
            if not requirement[field]:
                raise PlanError(f"direct routes require a non-empty requirement.{field}")
    query_variants = _string_list(
        value.get("query_variants", []),
        "query_variants",
        allow_empty_list=interaction_mode != "direct",
    )
    raw_platforms = value.get("platforms", [])
    if not isinstance(raw_platforms, list):
        raise PlanError("platforms must be a list")
    if interaction_mode == "direct" and not raw_platforms:
        raise PlanError("direct routes require at least one selected platform")

    platforms: list[dict[str, Any]] = []
    seen: set[str] = set()
    explicit_platforms = set(requirement["explicit_platforms"])
    for agent_platform in raw_platforms:
        if not isinstance(agent_platform, dict) or "platform_id" not in agent_platform:
            raise PlanError("each platform plan must include platform_id")
        canonical = canonicalize_platform(agent_platform["platform_id"])
        if explicit_platforms and canonical not in explicit_platforms:
            raise PlanError(
                f"selected platform {canonical!r} is outside explicit platform scope "
                f"{sorted(explicit_platforms)!r}"
            )
        if canonical in seen:
            raise PlanError(f"duplicate platform in Agent plan: {canonical}")
        seen.add(canonical)
        packet_input = dict(agent_platform)
        packet_input["_require_queries"] = interaction_mode == "direct"
        platforms.append(
            complete_dispatch_packet(packet_input, requirement=requirement, depth=value["depth"])
        )

    result: dict[str, Any] = {
        "requirement": requirement,
        "interaction_mode": interaction_mode,
        "scene": value["scene"],
        "depth": value["depth"],
        "query_variants": query_variants,
        "platforms": platforms,
        "router_path": value.get("router_path", []),
    }
    for field in ("request_summary", "context_summary", "selection_summary"):
        if field in value:
            result[field] = value[field]
    return result


def load_input(path: str) -> Any:
    try:
        stream = sys.stdin if path == "-" else open(path, "r", encoding="utf-8")
    except OSError as exc:
        raise PlanError(f"cannot open planner input: {exc}") from exc
    try:
        return json.load(stream)
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise PlanError(f"planner input is not valid JSON: {exc}") from exc
    finally:
        if stream is not sys.stdin:
            stream.close()


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("plan", nargs="?", default="-", help="Agent-generated JSON file, or - for stdin")
    args = parser.parse_args(argv[1:])
    try:
        resolved = resolve_route_plan(load_input(args.plan))
    except PlanError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    print(json.dumps(resolved, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
